About destructors and constructors
dead-seeds/Course2 pull request #18
Opened 2023-10-18 11:37 UTC by Maksim-Kotenkov

2023-10-18 12:29 UTC, TheBlek requested changes

2023-10-18 12:29 UTC, TheBlek commented on Pasted image 20231018181358.png
А почему он в корне лежит?

2023-10-18 12:29 UTC, TheBlek commented on Pasted image 20231018181358.png
Мы не хотим скрины осмысленно называть? Это бы облегчило поиск по папке со скринами, например.

2023-10-19 04:39 UTC, Maksim-Kotenkov commented on Pasted image 20231018181358.png
Оке, переименую и перемещу (они пастятся туда автоматом, кринж)

2023-10-20 03:14 UTC, TheBlek approved these changes

2023-10-20 04:08 UTC, merged